services:
  kosit-validator:
    image: apps4everything/kosit-validator-xrechnung:3.0.2-2@sha256:8cee7d3b246725ac365fd2f13483d14a01f547f7a513a7c6bb298fc0ab243383
    ports:
      - '8081:8081'

  verapdf-validator:
    image: verapdf/rest:v1.30.2@sha256:341359ac6af558f35f03c355a798fec57ba049dd04f0a503f300170e1696573b
    ports:
      - '8080:8080'
    healthcheck:
      test:
        - CMD-SHELL
        - wget --quiet --output-document=/dev/null http://127.0.0.1:8080/api/info || exit 1
      interval: 5s
      timeout: 5s
      retries: 20
